% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Lista 1 - Planejamento e Análise de Experimentos},
  pdfauthor={Bruno Mesquita dos Santo},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Lista 1 - Planejamento e Análise de Experimentos}
\author{Bruno Mesquita dos Santo}
\date{2024-02-26}

\begin{document}
\maketitle

\hypertarget{o-conjunto-de-dados-seguintes-uxe9-proveniente-de-um-experimento-conduzido-para-caracterizauxe7uxe3o-de-quatro-variedades-de-puxeara-a-b-c-e-d-com-relauxe7uxe3o-ao-peso-por-fruto-medido-em-gramas.-foi-colhida-uma-amostra-aleatuxf3ria-de-cinco-frutos-para-cada-variedade.-os-valores-obtidos-foram}{%
\paragraph{3) O conjunto de dados seguintes é proveniente de um
experimento conduzido para caracterização de quatro variedades de pêra
(A, B, C e D) com relação ao peso por fruto, medido em gramas. Foi
colhida uma amostra aleatória de cinco frutos para cada variedade. Os
valores obtidos
foram:}\label{o-conjunto-de-dados-seguintes-uxe9-proveniente-de-um-experimento-conduzido-para-caracterizauxe7uxe3o-de-quatro-variedades-de-puxeara-a-b-c-e-d-com-relauxe7uxe3o-ao-peso-por-fruto-medido-em-gramas.-foi-colhida-uma-amostra-aleatuxf3ria-de-cinco-frutos-para-cada-variedade.-os-valores-obtidos-foram}}

\begin{quote}
Repetições = 5 Tratamentos = 4
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tratA }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{78}\NormalTok{, }\DecValTok{88}\NormalTok{, }\DecValTok{72}\NormalTok{, }\DecValTok{74}\NormalTok{, }\DecValTok{98}\NormalTok{)}
\NormalTok{tratB }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{79}\NormalTok{, }\DecValTok{56}\NormalTok{, }\DecValTok{71}\NormalTok{, }\DecValTok{96}\NormalTok{, }\DecValTok{55}\NormalTok{)}
\NormalTok{tratC }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{63}\NormalTok{, }\DecValTok{68}\NormalTok{, }\DecValTok{58}\NormalTok{, }\DecValTok{79}\NormalTok{, }\DecValTok{59}\NormalTok{)}
\NormalTok{tratD }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{60}\NormalTok{, }\DecValTok{65}\NormalTok{, }\DecValTok{59}\NormalTok{, }\DecValTok{54}\NormalTok{, }\DecValTok{58}\NormalTok{)}
\NormalTok{X }\OtherTok{\textless{}{-}}\FunctionTok{c}\NormalTok{(tratA,tratB, tratC, tratD)}
\NormalTok{Y }\OtherTok{\textless{}{-}} \FunctionTok{rep}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"A"}\NormalTok{, }\StringTok{"B"}\NormalTok{, }\StringTok{"C"}\NormalTok{,}\StringTok{"D"}\NormalTok{), }\AttributeTok{each =} \DecValTok{5}\NormalTok{)}
\NormalTok{dados }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{Resp=}\NormalTok{X,}\AttributeTok{Trat=}\NormalTok{Y)}
\NormalTok{dados}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Resp Trat
## 1    78    A
## 2    88    A
## 3    72    A
## 4    74    A
## 5    98    A
## 6    79    B
## 7    56    B
## 8    71    B
## 9    96    B
## 10   55    B
## 11   63    C
## 12   68    C
## 13   58    C
## 14   79    C
## 15   59    C
## 16   60    D
## 17   65    D
## 18   59    D
## 19   54    D
## 20   58    D
\end{verbatim}

\hypertarget{a-testar-a-homogeneidade-de-variuxe2ncias-utilizando-o-teste-de-hartley.}{%
\subparagraph{a) Testar a homogeneidade de variâncias utilizando o Teste
de
Hartley.}\label{a-testar-a-homogeneidade-de-variuxe2ncias-utilizando-o-teste-de-hartley.}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{var}\NormalTok{(tratA) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 118
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{var}\NormalTok{(tratB)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 292.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{var}\NormalTok{(tratC) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 73.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{var}\NormalTok{(tratD) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 15.7
\end{verbatim}

Hcal = S²max/S²min

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Hcal }\OtherTok{\textless{}{-}} \FloatTok{292.3}\SpecialCharTok{/}\FloatTok{15.7}
\NormalTok{Hcal}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 18.61783
\end{verbatim}

Htab há 4 tratamento e (5-1)repetições por tratamento, a 5\% de
significância

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qmaxFratio}\NormalTok{(}\FloatTok{0.95}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 20.55922
\end{verbatim}

Como Hc\textless Htab, rejeita-se a hipotese de heterogeneidade de
variância dos grupos

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{b-se-o-teste-na-letra-a-nuxe3o-for-significativo-entuxe3o-obtenha-a-tabela-de-analise}{%
\subparagraph{b) Se o teste na letra a) não for significativo então
obtenha a tabela de
analise}\label{b-se-o-teste-na-letra-a-nuxe3o-for-significativo-entuxe3o-obtenha-a-tabela-de-analise}}

de variância, aplique o teste F e comente o resultado.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{modelo }\OtherTok{\textless{}{-}} \FunctionTok{aov}\NormalTok{(Resp}\SpecialCharTok{\textasciitilde{}}\NormalTok{Trat, }\AttributeTok{data =}\NormalTok{ dados)}
\FunctionTok{anova}\NormalTok{(modelo) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: Resp
##           Df Sum Sq Mean Sq F value  Pr(>F)  
## Trat       3 1413.8  471.27  3.7754 0.03188 *
## Residuals 16 1997.2  124.83                  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

Hipótese:

\[
\left\{ \begin{array}{rc} 
H0: \beta1 = \beta2 = \beta3 = \beta4 = 0 \\ 
H1: pelo \ menos \ um \ \beta \ difere \ de \ zero \\ 
\end{array}\right.
\]

Dado que nosso modelo possuí p-value: \textless{} 0.03188, podemos
concluir que há 5\% nível de significância ele rejeita H0, logo o modelo
é significativo.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{c-aplique-os-testes-teste-t-de-student-teste-de-tukey-teste-de-duncan-teste-de-s-n-k-teste-de-dunnett-considerando-o-tratamento-controle-sendo-a-e-o-teste-de-scheffuxe9.}{%
\subparagraph{c) Aplique os testes: Teste t de Student, Teste de Tukey,
Teste de Duncan, Teste de S-N-K, Teste de Dunnett (considerando o
tratamento controle sendo A) e o Teste de
Scheffé.}\label{c-aplique-os-testes-teste-t-de-student-teste-de-tukey-teste-de-duncan-teste-de-s-n-k-teste-de-dunnett-considerando-o-tratamento-controle-sendo-a-e-o-teste-de-scheffuxe9.}}

Teste t de Student:

\[
\left\{ \begin{array}{rc} 
H0: Y = 0 \\ 
H1: Y \neq 0
\end{array}\right.
\]

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(tratA,tratB)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  tratA and tratB
## t = 1.1701, df = 6.777, p-value = 0.2814
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -10.96414  32.16414
## sample estimates:
## mean of x mean of y 
##      82.0      71.4
\end{verbatim}

Aceita h0, logo a diferença das médias não é estatisticamente
significativa.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(tratA,tratC)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  tratA and tratC
## t = 2.6837, df = 7.5858, p-value = 0.02913
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   2.199586 31.000414
## sample estimates:
## mean of x mean of y 
##      82.0      65.4
\end{verbatim}

Rejeita h0, logo a diferença das médias é estatisticamente
significativa.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(tratA,tratD)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  tratA and tratD
## t = 4.4091, df = 5.0459, p-value = 0.006815
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   9.543613 36.056387
## sample estimates:
## mean of x mean of y 
##      82.0      59.2
\end{verbatim}

Rejeita h0, logo a diferença das médias é estatisticamente
significativa.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(tratB,tratC)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  tratB and tratC
## t = 0.70167, df = 5.8875, p-value = 0.5097
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -15.02093  27.02093
## sample estimates:
## mean of x mean of y 
##      71.4      65.4
\end{verbatim}

Aceita h0, logo a diferença das médias não é estatisticamente
significativa.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(tratB,tratD)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  tratB and tratD
## t = 1.5544, df = 4.4285, p-value = 0.1882
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -8.784296 33.184296
## sample estimates:
## mean of x mean of y 
##      71.4      59.2
\end{verbatim}

Aceita h0, logo a diferença das médias não é estatisticamente
significativa.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(tratC,tratD)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  tratC and tratD
## t = 1.4695, df = 5.6383, p-value = 0.1952
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -4.28619 16.68619
## sample estimates:
## mean of x mean of y 
##      65.4      59.2
\end{verbatim}

Aceita h0, logo a diferença das médias não é estatisticamente
significativa.

Utilizaremos o TratA por ter a maior média.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

Teste de Tukey:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{TukeyHSD}\NormalTok{(modelo)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = Resp ~ Trat, data = dados)
## 
## $Trat
##      diff      lwr       upr     p adj
## B-A -10.6 -30.8163  9.616299 0.4602137
## C-A -16.6 -36.8163  3.616299 0.1281553
## D-A -22.8 -43.0163 -2.583701 0.0244592
## C-B  -6.0 -26.2163 14.216299 0.8303280
## D-B -12.2 -32.4163  8.016299 0.3429223
## D-C  -6.2 -26.4163 14.016299 0.8163995
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}\FunctionTok{TukeyHSD}\NormalTok{(modelo))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Lista1_files/figure-latex/unnamed-chunk-17-1.pdf}

Somente D e A são diferentes entre si, como trat A tem maior média, ele
será usado

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

Teste de Duncan:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{resultado\_duncan }\OtherTok{\textless{}{-}} \FunctionTok{duncan.test}\NormalTok{(modelo, }\StringTok{"Trat"}\NormalTok{)}
\FunctionTok{print}\NormalTok{(resultado\_duncan)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $statistics
##   MSerror Df Mean       CV
##   124.825 16 69.5 16.07556
## 
## $parameters
##     test name.t ntr alpha
##   Duncan   Trat   4  0.05
## 
## $duncan
##      Table CriticalRange
## 2 2.997999      14.97950
## 3 3.143802      15.70801
## 4 3.234945      16.16340
## 
## $means
##   Resp       std r       se Min Max Q25 Q50 Q75
## A 82.0 10.862780 5 4.996499  72  98  74  78  88
## B 71.4 17.096783 5 4.996499  55  96  56  71  79
## C 65.4  8.561542 5 4.996499  58  79  59  63  68
## D 59.2  3.962323 5 4.996499  54  65  58  59  60
## 
## $comparison
## NULL
## 
## $groups
##   Resp groups
## A 82.0      a
## B 71.4     ab
## C 65.4      b
## D 59.2      b
## 
## attr(,"class")
## [1] "group"
\end{verbatim}

Diferença apenas entre o TratA - TratC e TratA - TratD.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

SNK

W1 = q(s/sqrt(r))

q = o valor na tabela de Tukey (nº de médias abrangidas pelo contraste,
nº de g.l.Resíduo) s = sqrt(qmerro) r = numero de repetições

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{q }\OtherTok{\textless{}{-}} \FunctionTok{qtukey}\NormalTok{(}\FloatTok{0.95}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{16}\NormalTok{) }
\NormalTok{s }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}\FloatTok{124.83}\NormalTok{)}
\NormalTok{r }\OtherTok{\textless{}{-}} \DecValTok{5}
\FunctionTok{print}\NormalTok{(q}\SpecialCharTok{*}\NormalTok{(s}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(r)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 20.2167
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(tratA)}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(tratD)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 22.8
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(tratA)}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(tratC)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 16.6
\end{verbatim}

Como Yestimado\textgreater(contraste de duas médias) então rejeita-se
H0. logo MA != MD, mas H0 é aceito entre MA, MB e MC

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

DUNNET

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{DunnettTest}\NormalTok{(}\FunctionTok{list}\NormalTok{(tratA, tratB, tratC, tratD))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##   Dunnett's test for comparing several treatments with a control :  
##     95% family-wise confidence level
## 
## $`1`
##      diff    lwr.ci    upr.ci   pval    
## 2-1 -10.6 -28.91969  7.719687 0.3361    
## 3-1 -16.6 -34.91969  1.719687 0.0797 .  
## 4-1 -22.8 -41.11969 -4.480313 0.0140 *  
## 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

A média do tratD é significativamente diferente da média tratA, mas as
médias do TratB e C não diferem significativamente.

\hypertarget{para-avaliar-a-condiuxe7uxe3o-de-fertilidade-do-solo-de-uma-propriedade-rural-foram-coletadas-quatro-amostras-de-cada-um-dos-cinco-tipos-de-solos.-os-valores-obtidos-para-o-teor-de-carbono-orguxe2nico-em-g.kg-1-em-cada-solo-foram}{%
\paragraph{4) Para avaliar a condição de fertilidade do solo de uma
propriedade rural foram coletadas quatro amostras de cada um dos cinco
tipos de solos. Os valores obtidos para o teor de carbono orgânico, em
g.kg-1, em cada solo,
foram:}\label{para-avaliar-a-condiuxe7uxe3o-de-fertilidade-do-solo-de-uma-propriedade-rural-foram-coletadas-quatro-amostras-de-cada-um-dos-cinco-tipos-de-solos.-os-valores-obtidos-para-o-teor-de-carbono-orguxe2nico-em-g.kg-1-em-cada-solo-foram}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{22}\NormalTok{, }\DecValTok{25}\NormalTok{, }\DecValTok{23}\NormalTok{, }\DecValTok{26}\NormalTok{)}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{( }\DecValTok{24}\NormalTok{, }\DecValTok{27}\NormalTok{, }\DecValTok{25}\NormalTok{, }\DecValTok{29}\NormalTok{)}
\NormalTok{C }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{( }\DecValTok{20}\NormalTok{, }\DecValTok{22}\NormalTok{, }\DecValTok{23}\NormalTok{, }\DecValTok{21}\NormalTok{)}
\NormalTok{D }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{( }\DecValTok{26}\NormalTok{, }\DecValTok{28}\NormalTok{, }\DecValTok{30}\NormalTok{, }\DecValTok{29}\NormalTok{)}
\NormalTok{E }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{26}\NormalTok{, }\DecValTok{23}\NormalTok{, }\DecValTok{21}\NormalTok{, }\DecValTok{23}\NormalTok{)}

\NormalTok{X}\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(A,B,C,D,E)}
\NormalTok{Y }\OtherTok{\textless{}{-}} \FunctionTok{rep}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"A"}\NormalTok{, }\StringTok{"B"}\NormalTok{, }\StringTok{"C"}\NormalTok{, }\StringTok{"D"}\NormalTok{, }\StringTok{"E"}\NormalTok{), }\AttributeTok{each =} \DecValTok{4}\NormalTok{)}
\NormalTok{dados }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{Resp=}\NormalTok{X,}\AttributeTok{Trat=}\NormalTok{Y)}
\NormalTok{dados}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Resp Trat
## 1    22    A
## 2    25    A
## 3    23    A
## 4    26    A
## 5    24    B
## 6    27    B
## 7    25    B
## 8    29    B
## 9    20    C
## 10   22    C
## 11   23    C
## 12   21    C
## 13   26    D
## 14   28    D
## 15   30    D
## 16   29    D
## 17   26    E
## 18   23    E
## 19   21    E
## 20   23    E
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{shapiro.test}\NormalTok{(dados}\SpecialCharTok{$}\NormalTok{Resp) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  dados$Resp
## W = 0.95566, p-value = 0.4612
\end{verbatim}

pvalor maior que 0.05, dados estão normais(H0)

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{bartlett.test}\NormalTok{(Resp}\SpecialCharTok{\textasciitilde{}}\NormalTok{Trat, }\AttributeTok{data=}\NormalTok{dados)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Bartlett test of homogeneity of variances
## 
## data:  Resp by Trat
## Bartlett's K-squared = 0.84319, df = 4, p-value = 0.9326
\end{verbatim}

pvalor maior que 0.05, dados tem homogeneidade(H0)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{modelo }\OtherTok{\textless{}{-}} \FunctionTok{aov}\NormalTok{(Resp}\SpecialCharTok{\textasciitilde{}}\NormalTok{Trat, }\AttributeTok{data =}\NormalTok{ dados)}
\FunctionTok{anova}\NormalTok{(modelo) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: Resp
##           Df Sum Sq Mean Sq F value   Pr(>F)   
## Trat       4 111.30 27.8250  8.1439 0.001067 **
## Residuals 15  51.25  3.4167                    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{quote}
Fcalc\textless- 27.8250/3.4167 \#8.143823 qf(0.95,4,15) \#3.055568 Como
Fcal\textgreater Ftab, rejeita-se H0, logo, pelo menos, um tratamento
difere dos outros
\end{quote}

\hypertarget{um-experimento-foi-conduzido-para-avaliar-diferentes-muxe9todos-de-conservauxe7uxe3o-das-espiguetas-de-mini-milho-com-a-finalidade-de-proporcionar-um-produto-com-qualidade.-foi-utilizado-o-delineamento-inteiramente-casualizado-com-quatro-repetiuxe7uxf5es-sendo-as-parcelas-constituuxeddas-por-truxeas-embalagens-contendo-cada-uma-15-espiguetas.-a-variuxe1vel-medida-foi-o-teor-de-vitamina-c.-os-tratamentos-e-os-valores-de-vitamina-c-em-mg100g-obtidos-foram}{%
\paragraph{5) Um experimento foi conduzido para avaliar diferentes
métodos de conservação das espiguetas de mini milho com a finalidade de
proporcionar um produto com qualidade. Foi utilizado o delineamento
inteiramente casualizado, com quatro repetições, sendo as parcelas
constituídas por três embalagens, contendo cada uma, 15 espiguetas. A
variável medida foi o teor de vitamina C. Os tratamentos e os valores de
vitamina C, em mg/100g, obtidos
foram:}\label{um-experimento-foi-conduzido-para-avaliar-diferentes-muxe9todos-de-conservauxe7uxe3o-das-espiguetas-de-mini-milho-com-a-finalidade-de-proporcionar-um-produto-com-qualidade.-foi-utilizado-o-delineamento-inteiramente-casualizado-com-quatro-repetiuxe7uxf5es-sendo-as-parcelas-constituuxeddas-por-truxeas-embalagens-contendo-cada-uma-15-espiguetas.-a-variuxe1vel-medida-foi-o-teor-de-vitamina-c.-os-tratamentos-e-os-valores-de-vitamina-c-em-mg100g-obtidos-foram}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{AD }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{7}\NormalTok{, }\DecValTok{9}\NormalTok{, }\DecValTok{10}\NormalTok{, }\DecValTok{9}\NormalTok{)}
\NormalTok{AA }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{18}\NormalTok{, }\DecValTok{20}\NormalTok{, }\DecValTok{17}\NormalTok{, }\DecValTok{17}\NormalTok{)}
\NormalTok{LC }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{15}\NormalTok{, }\DecValTok{14}\NormalTok{, }\DecValTok{15}\NormalTok{, }\DecValTok{13}\NormalTok{)}
\NormalTok{AAR }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{9}\NormalTok{, }\DecValTok{7}\NormalTok{, }\DecValTok{10}\NormalTok{, }\DecValTok{8}\NormalTok{)}
\NormalTok{LCR }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{9}\NormalTok{, }\DecValTok{8}\NormalTok{, }\DecValTok{10}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{a-elabore-um-conjunto-de-contrastes-ortogonais-uxfateis-para-o-pesquisador}{%
\subparagraph{a) Elabore um conjunto de contrastes ortogonais úteis para
o
pesquisador:}\label{a-elabore-um-conjunto-de-contrastes-ortogonais-uxfateis-para-o-pesquisador}}

Y = 4m1 - m2 - m3 - m4 - m5 h0 = y = 0 \textless=\textgreater{} m1 = (m2
+ m3 + m4 + m5)/4

Y2 = m1 - m2 h0 = y2 = 0 \textless=\textgreater{} m1 = m2

\hypertarget{b-explique-o-significado-de-cada-contraste}{%
\subparagraph{b) Explique o significado de cada
contraste:}\label{b-explique-o-significado-de-cada-contraste}}

O contraste Y verifica ser a media do tratamento 1 é igual a média dos
tratamentos restantes. Já o Y2 verifica a igualdade da média de dois
tratamentos.

\hypertarget{c-elabore-a-anuxe1lise-da-variuxe2ncia-com-interpretauxe7uxe3o-dos-resultados}{%
\subparagraph{c) Elabore a análise da variância, com interpretação dos
resultados:}\label{c-elabore-a-anuxe1lise-da-variuxe2ncia-com-interpretauxe7uxe3o-dos-resultados}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{X}\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(AD,AA,LC,AAR,LCR)}
\NormalTok{Y }\OtherTok{\textless{}{-}} \FunctionTok{rep}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"A"}\NormalTok{, }\StringTok{"B"}\NormalTok{, }\StringTok{"C"}\NormalTok{, }\StringTok{"D"}\NormalTok{, }\StringTok{"E"}\NormalTok{), }\AttributeTok{each =} \DecValTok{4}\NormalTok{)}
\NormalTok{dados }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{Resp=}\NormalTok{X,}\AttributeTok{Trat=}\NormalTok{Y)}
\NormalTok{dados}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Resp Trat
## 1     7    A
## 2     9    A
## 3    10    A
## 4     9    A
## 5    18    B
## 6    20    B
## 7    17    B
## 8    17    B
## 9    15    C
## 10   14    C
## 11   15    C
## 12   13    C
## 13    9    D
## 14    7    D
## 15   10    D
## 16    8    D
## 17    9    E
## 18    8    E
## 19   10    E
## 20   10    E
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{shapiro.test}\NormalTok{(dados}\SpecialCharTok{$}\NormalTok{Resp) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  dados$Resp
## W = 0.88768, p-value = 0.02438
\end{verbatim}

pvalor menor que 0.05, dados não estão normais(H0)

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{bartlett.test}\NormalTok{(Resp}\SpecialCharTok{\textasciitilde{}}\NormalTok{Trat, }\AttributeTok{data=}\NormalTok{dados)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Bartlett test of homogeneity of variances
## 
## data:  Resp by Trat
## Bartlett's K-squared = 0.66719, df = 4, p-value = 0.9553
\end{verbatim}

pvalor maior que 0.05, dados tem homogeneidade(H0)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{modelo }\OtherTok{\textless{}{-}} \FunctionTok{aov}\NormalTok{(Resp}\SpecialCharTok{\textasciitilde{}}\NormalTok{Trat, }\AttributeTok{data =}\NormalTok{ dados)}
\FunctionTok{anova}\NormalTok{(modelo) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: Resp
##           Df Sum Sq Mean Sq F value    Pr(>F)    
## Trat       4 284.50  71.125  50.206 1.648e-08 ***
## Residuals 15  21.25   1.417                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

Hipótese:

\[
\left\{ \begin{array}{rc} 
H0: \beta1 = \beta2 = \beta3 = \beta4 = 0 \\ 
H1: pelo \ menos \ um \ \beta \ difere \ de \ zero \\ 
\end{array}\right.
\]

Dado que nosso modelo possuí p-value: 1.648e-08 \textless{} 0.05,
podemos concluir que há 5\% nível de significância ele rejeita H0, logo
o modelo é significativo.

\hypertarget{d-aplique-o-teste-de-tukey-5-e-o-teste-snk-5.-comente-os-resultados.}{%
\subparagraph{d) Aplique o teste de Tukey (5\%) e o teste SNK (5\%).
Comente os
resultados.}\label{d-aplique-o-teste-de-tukey-5-e-o-teste-snk-5.-comente-os-resultados.}}

Tukey:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{TukeyHSD}\NormalTok{(modelo)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = Resp ~ Trat, data = dados)
## 
## $Trat
##      diff        lwr       upr     p adj
## B-A  9.25   6.651124 11.848876 0.0000001
## C-A  5.50   2.901124  8.098876 0.0000799
## D-A -0.25  -2.848876  2.348876 0.9981018
## E-A  0.50  -2.098876  3.098876 0.9738847
## C-B -3.75  -6.348876 -1.151124 0.0036007
## D-B -9.50 -12.098876 -6.901124 0.0000001
## E-B -8.75 -11.348876 -6.151124 0.0000003
## D-C -5.75  -8.348876 -3.151124 0.0000483
## E-C -5.00  -7.598876 -2.401124 0.0002256
## E-D  0.75  -1.848876  3.348876 0.8957929
\end{verbatim}

B-A, C-A, C-B, D-B, E-B, D-C, E-C são diferentes entre si/

SNK

W1 = q(s/sqrt(r))

q = o valor na tabela de Tukey (nº de médias abrangidas pelo contraste,
nº de g.l.Resíduo) s = sqrt(qmerro) r = numero de repetições

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{q }\OtherTok{\textless{}{-}} \FunctionTok{qtukey}\NormalTok{(}\FloatTok{0.95}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{15}\NormalTok{) }
\NormalTok{s }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}\FloatTok{1.417}\NormalTok{)}
\NormalTok{r }\OtherTok{\textless{}{-}} \DecValTok{4}
\FunctionTok{print}\NormalTok{(q}\SpecialCharTok{*}\NormalTok{(s}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(r)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.599181
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(AD)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 8.75
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(AA)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 18
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(LC)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 14.25
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(AAR)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 8.5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(LCR)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9.25
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(LCR)}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(AAR)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.75
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(LCR)}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(AD)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(AD)}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(AAR)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.25
\end{verbatim}

mean(AD) Como Yestimado\textgreater(contraste de duas médias) então
rejeita-se H0. logo LC != AA, mas H0 é aceito entre LCR, AD e AAR

\hypertarget{um-experimento-foi-conduzido-no-delineamento-inteiramente-casualizado-com-quatro-repetiuxe7uxf5es-para-o-desenvolvimento-de-peixe-tipo-lambari-quando-tratados-por-diferentes-rauxe7uxf5es.-os-tratamentos-e-valores-de-comprimento-dos-peixes-em-cm-foram}{%
\paragraph{6) Um experimento foi conduzido no delineamento inteiramente
casualizado, com quatro repetições, para o desenvolvimento de peixe tipo
lambari quando tratados por diferentes rações. Os tratamentos e valores
de comprimento dos peixes, em cm,
foram:}\label{um-experimento-foi-conduzido-no-delineamento-inteiramente-casualizado-com-quatro-repetiuxe7uxf5es-para-o-desenvolvimento-de-peixe-tipo-lambari-quando-tratados-por-diferentes-rauxe7uxf5es.-os-tratamentos-e-valores-de-comprimento-dos-peixes-em-cm-foram}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{RC }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{( }\FloatTok{4.6}\NormalTok{, }\FloatTok{5.1}\NormalTok{, }\FloatTok{5.8}\NormalTok{, }\FloatTok{5.5}\NormalTok{)}
\NormalTok{RCE }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{( }\FloatTok{6.0}\NormalTok{, }\FloatTok{7.1}\NormalTok{, }\FloatTok{7.2}\NormalTok{, }\FloatTok{6.8}\NormalTok{)}
\NormalTok{RCEV }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{( }\FloatTok{5.8}\NormalTok{, }\FloatTok{7.2}\NormalTok{, }\FloatTok{6.9}\NormalTok{, }\FloatTok{6.7}\NormalTok{)}
\NormalTok{RCF }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FloatTok{5.6}\NormalTok{, }\FloatTok{4.9}\NormalTok{, }\FloatTok{5.9}\NormalTok{, }\FloatTok{5.7}\NormalTok{)}
\NormalTok{RCFV }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FloatTok{1.0}\NormalTok{, }\FloatTok{5.5}\NormalTok{, }\FloatTok{5.1}\NormalTok{, }\FloatTok{5.9}\NormalTok{)}

\NormalTok{X }\OtherTok{\textless{}{-}}\FunctionTok{c}\NormalTok{(RC, RCE, RCEV, RCF, RCFV)}
\NormalTok{Y }\OtherTok{\textless{}{-}} \FunctionTok{rep}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"A"}\NormalTok{, }\StringTok{"B"}\NormalTok{, }\StringTok{"C"}\NormalTok{,}\StringTok{"D"}\NormalTok{, }\StringTok{"E"}\NormalTok{), }\AttributeTok{each =} \DecValTok{4}\NormalTok{)}
\NormalTok{dados }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{Resp=}\NormalTok{X,}\AttributeTok{Trat=}\NormalTok{Y)}
\NormalTok{dados}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Resp Trat
## 1   4.6    A
## 2   5.1    A
## 3   5.8    A
## 4   5.5    A
## 5   6.0    B
## 6   7.1    B
## 7   7.2    B
## 8   6.8    B
## 9   5.8    C
## 10  7.2    C
## 11  6.9    C
## 12  6.7    C
## 13  5.6    D
## 14  4.9    D
## 15  5.9    D
## 16  5.7    D
## 17  1.0    E
## 18  5.5    E
## 19  5.1    E
## 20  5.9    E
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{modelo }\OtherTok{\textless{}{-}} \FunctionTok{aov}\NormalTok{(Resp}\SpecialCharTok{\textasciitilde{}}\NormalTok{Trat, }\AttributeTok{data =}\NormalTok{ dados)}
\FunctionTok{anova}\NormalTok{(modelo) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: Resp
##           Df Sum Sq Mean Sq F value  Pr(>F)  
## Trat       4 16.183  4.0458  3.2173 0.04285 *
## Residuals 15 18.863  1.2575                  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

Dado que nosso modelo possuí p-value: \textless{} 0.04285, podemos
concluir que há 5\% nível de significância ele rejeita H0, logo o modelo
é significativo.

\hypertarget{um-experimento-foi-conduzido-no-delineamento-inteiramente-casualizado-com-cinco-repetiuxe7uxf5es-para-avaliar-o-efeito-de-cinco-medicamentos-na-diminuiuxe7uxe3o-da-pressuxe3o-arterial-de-animais-experimentais.-para-isso-o-pesquisador-escolheu-ao-acaso-30-animais-do-mesmo-tipo-e-dividiu-ao-acaso-em-seis-grupos-sendo-que-em-cada-grupo-os-animais-receberam-o-mesmo-medicamento.-exceto-pelos-medicamentos-identificados-por-a-b-c-d-e-e-t-todos-os-animais-tiveram-o-mesmo-cuidado-e-mesma-alimentauxe7uxe3o-sendo-criados-na-mesma-uxe1rea-experimental.-apuxf3s-o-peruxedodo-de-avaliauxe7uxe3o-os-animais-sorteados-na-uxe1rea-experimental-bem-como-os-tratamentos-e-os-valores-da-pressuxe3o-arterial-foram}{%
\paragraph{7) Um experimento foi conduzido no delineamento inteiramente
casualizado, com cinco repetições, para avaliar o efeito de cinco
medicamentos na diminuição da pressão arterial de animais experimentais.
Para isso, o pesquisador escolheu ao acaso 30 animais do mesmo tipo e
dividiu ao acaso em seis grupos, sendo que em cada grupo os animais
receberam o mesmo medicamento. Exceto pelos medicamentos (identificados
por A, B, C, D, E e T), todos os animais tiveram o mesmo cuidado e mesma
alimentação, sendo criados na mesma área experimental. Após o período de
avaliação, os animais sorteados na área experimental bem como os
tratamentos e os valores da pressão arterial
foram:}\label{um-experimento-foi-conduzido-no-delineamento-inteiramente-casualizado-com-cinco-repetiuxe7uxf5es-para-avaliar-o-efeito-de-cinco-medicamentos-na-diminuiuxe7uxe3o-da-pressuxe3o-arterial-de-animais-experimentais.-para-isso-o-pesquisador-escolheu-ao-acaso-30-animais-do-mesmo-tipo-e-dividiu-ao-acaso-em-seis-grupos-sendo-que-em-cada-grupo-os-animais-receberam-o-mesmo-medicamento.-exceto-pelos-medicamentos-identificados-por-a-b-c-d-e-e-t-todos-os-animais-tiveram-o-mesmo-cuidado-e-mesma-alimentauxe7uxe3o-sendo-criados-na-mesma-uxe1rea-experimental.-apuxf3s-o-peruxedodo-de-avaliauxe7uxe3o-os-animais-sorteados-na-uxe1rea-experimental-bem-como-os-tratamentos-e-os-valores-da-pressuxe3o-arterial-foram}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{a }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{21}\NormalTok{,}\DecValTok{23}\NormalTok{,}\DecValTok{26}\NormalTok{,}\DecValTok{21}\NormalTok{,}\DecValTok{22}\NormalTok{)}
\NormalTok{b }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{8}\NormalTok{,}\DecValTok{10}\NormalTok{,}\DecValTok{6}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{9}\NormalTok{)}
\NormalTok{c }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{11}\NormalTok{,}\DecValTok{10}\NormalTok{,}\DecValTok{14}\NormalTok{,}\DecValTok{14}\NormalTok{,}\DecValTok{12}\NormalTok{)}
\NormalTok{d }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{29}\NormalTok{,}\DecValTok{25}\NormalTok{,}\DecValTok{31}\NormalTok{,}\DecValTok{33}\NormalTok{,}\DecValTok{30}\NormalTok{)}
\NormalTok{e }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{12}\NormalTok{,}\DecValTok{13}\NormalTok{,}\DecValTok{15}\NormalTok{,}\DecValTok{11}\NormalTok{,}\DecValTok{15}\NormalTok{)}
\NormalTok{t }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{)}

\NormalTok{X }\OtherTok{\textless{}{-}}\FunctionTok{c}\NormalTok{(a, b, c, d, e, t)}
\NormalTok{Y }\OtherTok{\textless{}{-}} \FunctionTok{rep}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"A"}\NormalTok{, }\StringTok{"B"}\NormalTok{, }\StringTok{"C"}\NormalTok{,}\StringTok{"D"}\NormalTok{, }\StringTok{"E"}\NormalTok{, }\StringTok{"T"}\NormalTok{), }\AttributeTok{each =} \DecValTok{5}\NormalTok{)}
\NormalTok{dados }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{Resp=}\NormalTok{X,}\AttributeTok{Trat=}\NormalTok{Y)}
\NormalTok{dados}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Resp Trat
## 1    21    A
## 2    23    A
## 3    26    A
## 4    21    A
## 5    22    A
## 6     8    B
## 7    10    B
## 8     6    B
## 9     0    B
## 10    9    B
## 11   11    C
## 12   10    C
## 13   14    C
## 14   14    C
## 15   12    C
## 16   29    D
## 17   25    D
## 18   31    D
## 19   33    D
## 20   30    D
## 21   12    E
## 22   13    E
## 23   15    E
## 24   11    E
## 25   15    E
## 26    2    T
## 27    4    T
## 28    0    T
## 29    2    T
## 30    2    T
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{shapiro.test}\NormalTok{(dados}\SpecialCharTok{$}\NormalTok{Resp) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  dados$Resp
## W = 0.94745, p-value = 0.1444
\end{verbatim}

pvalor maior que 0.05, dados estão normais(H0)

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{bartlett.test}\NormalTok{(Resp}\SpecialCharTok{\textasciitilde{}}\NormalTok{Trat, }\AttributeTok{data=}\NormalTok{dados)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Bartlett test of homogeneity of variances
## 
## data:  Resp by Trat
## Bartlett's K-squared = 5.6527, df = 5, p-value = 0.3415
\end{verbatim}

pvalor maior que 0.05, dados tem homogeneidade(H0)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{modelo }\OtherTok{\textless{}{-}} \FunctionTok{aov}\NormalTok{(Resp}\SpecialCharTok{\textasciitilde{}}\NormalTok{Trat, }\AttributeTok{data =}\NormalTok{ dados)}
\FunctionTok{anova}\NormalTok{(modelo) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: Resp
##           Df Sum Sq Mean Sq F value    Pr(>F)    
## Trat       5 2595.8  519.15   83.51 2.232e-14 ***
## Residuals 24  149.2    6.22                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

Dado que nosso modelo possuí p-value: 2.232e-14 \textless{} 0.05,
podemos concluir que há 5\% nível de significância ele rejeita H0, logo
o modelo é significativo.

\hypertarget{um-experimento-foi-conduzido-no-delineamento-em-blocos-casualizado-com-truxeas-repetiuxe7uxf5es-para-estudar-diferentes-muxe9todos-de-controle-de-plantas-daninhas-sobre-a-produuxe7uxe3o-de-gruxe3os-de-milho.-os-tratamentos-e-valores-de-produuxe7uxe3o-de-gruxe3os-tha-foram}{%
\paragraph{8) Um experimento foi conduzido no delineamento em blocos
casualizado, com três repetições, para estudar diferentes métodos de
controle de plantas daninhas sobre a produção de grãos de milho. Os
tratamentos e valores de produção de grãos (t/ha)
foram:}\label{um-experimento-foi-conduzido-no-delineamento-em-blocos-casualizado-com-truxeas-repetiuxe7uxf5es-para-estudar-diferentes-muxe9todos-de-controle-de-plantas-daninhas-sobre-a-produuxe7uxe3o-de-gruxe3os-de-milho.-os-tratamentos-e-valores-de-produuxe7uxe3o-de-gruxe3os-tha-foram}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SC }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{( }\FloatTok{2.9}\NormalTok{, }\FloatTok{3.2}\NormalTok{, }\FloatTok{2.4}\NormalTok{)}
\NormalTok{CM }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{( }\FloatTok{8.0}\NormalTok{, }\FloatTok{10.6}\NormalTok{, }\FloatTok{9.8}\NormalTok{)}
\NormalTok{HA\_5 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FloatTok{5.6}\NormalTok{, }\FloatTok{6.0}\NormalTok{, }\FloatTok{6.7}\NormalTok{)}
\NormalTok{HB\_1 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{( }\FloatTok{7.7}\NormalTok{, }\FloatTok{8.8}\NormalTok{, }\FloatTok{7.9}\NormalTok{)}
\NormalTok{HB\_5 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{( }\FloatTok{4.3}\NormalTok{, }\FloatTok{6.5}\NormalTok{, }\FloatTok{5.6}\NormalTok{)}
\NormalTok{HB\_1 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{( }\FloatTok{5.5}\NormalTok{, }\FloatTok{5.1}\NormalTok{, }\FloatTok{6.9}\NormalTok{)}
\end{Highlighting}
\end{Shaded}


\end{document}
